"""
app/models/user.py — User table definition.

Maps to the 'users' table in PostgreSQL.
Every authenticated user in the system has one row here.

Relationships:
    User → LLMKey  (one-to-many)  user.llm_keys
    User → Document (one-to-many) user.documents  (added Phase 3)
    User → Session  (one-to-many) user.sessions   (added Phase 9)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, Float, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base

# TYPE_CHECKING block avoids circular imports at runtime.
# LLMKey imports User, so we cannot import LLMKey here at module level.
# The string "LLMKey" in relationship() is resolved lazily by SQLAlchemy.
if TYPE_CHECKING:
    from app.models.llm_key import LLMKey


class User(Base):
    """
    Represents one registered user account.

    Budget columns (daily_budget_usd, monthly_budget_usd):
        These are checked by the cost guard in Phase 5 before every LLM call.
        Default None = unlimited. Set a value to cap spend per user.

    Preferences column (JSONB):
        Stores user settings as a flexible JSON object.
        Avoids schema migrations every time we add a new preference.
        Example: {"theme": "dark", "default_provider": "groq", "language": "en"}

    Role column:
        "user"  → standard access
        "admin" → access to admin routes (Phase 10)
        Checked in get_current_admin_user() dependency.
    """

    __tablename__ = "users"

    # ── Primary key ──────────────────────────────────────────
    # UUID generated by PostgreSQL (uuid-ossp extension enabled in init_db.py)
    # server_default means PostgreSQL generates it — not Python
    # This avoids any clock/randomness issues at the application layer
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Unique user identifier — UUID v4 generated by PostgreSQL",
    )

    # ── Authentication ────────────────────────────────────────
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,  # Index for fast login lookup by email
        comment="User email address — used as login identifier",
    )

    hashed_password: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="bcrypt hash of the user password — never store plain text",
    )

    # ── Profile ───────────────────────────────────────────────
    full_name: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        comment="Optional display name shown in the UI",
    )

    # ── Access control ────────────────────────────────────────
    role: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        server_default="user",
        comment="Access role: 'user' (default) or 'admin'",
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="true",
        comment=(
            "Account active flag. Set to false to disable without deleting. "
            "Inactive users cannot log in — get_current_user raises 403."
        ),
    )

    # ── LLM Budget controls ───────────────────────────────────
    # Checked by cost_guard in Phase 5 before every LLM call.
    # None = unlimited. Set a float value to cap spend.
    daily_budget_usd: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment=(
            "Maximum USD to spend on LLM calls per calendar day (UTC). "
            "None = unlimited. Enforced by cost_guard middleware in Phase 5."
        ),
    )

    monthly_budget_usd: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment=(
            "Maximum USD to spend on LLM calls per calendar month (UTC). "
            "None = unlimited. Enforced by cost_guard middleware in Phase 5."
        ),
    )

    # ── Flexible preferences ──────────────────────────────────
    # JSONB = binary JSON in PostgreSQL — indexed, queryable, fast
    # Prefer JSONB over JSON for any column you might query inside
    preferences: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        server_default="{}",
        comment=(
            "Flexible user preferences stored as JSON. "
            "Example: {'theme': 'dark', 'default_provider': 'groq'}"
        ),
    )

    # ── Timestamps ────────────────────────────────────────────
    # server_default → PostgreSQL generates using its own clock (UTC)
    # onupdate       → SQLAlchemy automatically updates on every save
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp when the account was created (UTC)",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp of last modification — auto-updated by SQLAlchemy",
    )

    # ── Relationships ─────────────────────────────────────────
    # lazy="selectin" → when you load a User, SQLAlchemy automatically
    # runs a second SELECT to load their llm_keys in one extra query.
    # This is safer than lazy="dynamic" for async code.
    # back_populates connects the two sides of the relationship.
    llm_keys: Mapped[list["LLMKey"]] = relationship(
        "LLMKey",
        back_populates="user",
        lazy="selectin",
        cascade="all, delete-orphan",
        comment="All LLM API keys stored by this user (BYOK pattern)",
    )

    # Documents relationship added in Phase 3 when Document model exists
    # documents: Mapped[list["Document"]] = relationship(...)

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email} role={self.role}>"

    @property
    def is_admin(self) -> bool:
        """Convenience property — avoids string comparison in routes."""
        return self.role == "admin"